version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres.bookstoreapp.test
    command: postgres -c max_connections=200
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      ENV: ${ENV:-develop}
    volumes:
      - ./config/postgresql/data:/var/lib/postgresql/data
      - ./config/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432