// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package models

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context, id int32) (User, error)
	GetAccount(ctx context.Context, id int32) (User, error)
	LoginAccount(ctx context.Context, arg LoginAccountParams) (User, error)
}

var _ Querier = (*Queries)(nil)
