// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: user.sql

package models

import (
	"context"
)

const loginAccount = `-- name: LoginAccount :one
SELECT "ID", first_name, last_name, email, username, birthday, height, status, gender, password, created_at, updated_at
FROM public."User" as u
Where u.email = $1 AND u.password = $2
`

type LoginAccountParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) LoginAccount(ctx context.Context, arg LoginAccountParams) (User, error) {
	row := q.db.QueryRowContext(ctx, loginAccount, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Username,
		&i.Birthday,
		&i.Height,
		&i.Status,
		&i.Gender,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
